Docs: Update authentication.erb
googleapis/gapic-generator-ruby pull request #1022
Opened 2024-01-03 19:25 UTC by piaxc

Update authentication guidance to conform to Cloud authentication documentation and highlight ADC.

b/266978558

2024-01-03 20:04 UTC, dazuma requested changes

2024-01-03 20:04 UTC, dazuma commented on gapic-generator-cloud/templates/cloud/gem/authentication.erb
> +you can include the credentials file itself.
"it can contain the credentials file contents."

2024-01-03 20:04 UTC, dazuma commented on gapic-generator-cloud/templates/cloud/gem/authentication.erb
> +The JSON credentials file can be an credential file as created for
Same comment as above.

2024-01-03 20:04 UTC, dazuma commented on gapic-generator-cloud/templates/cloud/gem/authentication.erb
> +local ADC credentials are discovered.
nit: Can you wrap this paragraph a bit better?

2024-01-03 20:36 UTC, piaxc commented on gapic-generator-cloud/templates/cloud/gem/authentication.erb
> +XXX
Yup, thanks, meant to do that.

2024-01-04 20:01 UTC, dazuma approved these changes

2024-01-04 23:50 UTC, merged