fix: the authentication.md link
googleapis/gapic-generator-ruby pull request #560
Opened 2021-02-25 02:48 UTC by viacheslav-rostovtsev

2021-02-25 15:53 UTC, quartzmo reviewed
Will there be a post-generation step to convert the markdown link back to a YARD link for the YARD output?

2021-02-25 16:26 UTC, dazuma requested changes
Yes, this needs to be coupled with a build process change that replaces these links with the yardoc form before building the gem.

Probably the best way to do this is to replace the build rake task in the generated rakefiles. (Currently the task is defined by requiring `"bundler/gem_tasks"`. We can just remove that and write our own task that copies the gem directory off to a temporary directory, makes the necessary README modifications, runs `gem build` on the gemspec, and copies the built gem back into the original gem directory's `pkg`.)

2021-04-21 19:59 UTC, dazuma commented
Sorry, I forgot about this. We do still need to do this. Tram got the build process change in, so we can make this change to the generator now.

2021-04-21 23:46 UTC, dazuma approved these changes

2021-04-22 20:17 UTC, merged