docs: Add test and linting steps to README [ggr]
googleapis/gapic-generator-ruby pull request #634
Opened 2021-07-26 21:49 UTC by miraleung

2021-08-05 18:44 UTC, viacheslav-rostovtsev requested changes
If we are to add a developer guide, it needs to cover more ground, mentioning at least the generator structure and describing the development workflow, e.g. protos vs bin, unit tests vs gold tests, vs unit-tests-on-gold vs showcase. 

As it is, it's only useful to a very narrow scope of potential developers, not to mention being wrong, e.g. 
`bundle exec rake test TEST=path/to/test/file.rb` does not do what this says when run from the root of the project, and the distinction of root vs subgenerator is not described in the guide.

2021-08-05 18:44 UTC, viacheslav-rostovtsev commented on README.md
> +$ bundle exec rake test TEST=path/to/test/file.rb
This does not work from the root

2021-08-05 19:56 UTC, miraleung commented on README.md
> +$ bundle exec rake test TEST=path/to/test/file.rb
Fixed.

2021-08-05 20:25 UTC, miraleung commented
This PR is meant to incrementally add developer steps that would aid in setting up and working with this codebase. A full developer guide could come as a result of similar accumulated incremental changes, or this PR could make such an effort easier.

2021-08-06 20:20 UTC, viacheslav-rostovtsev approved these changes

2021-08-06 20:31 UTC, merged