feat: implement templates changes for regapic streaming.
googleapis/gapic-generator-ruby pull request #821
Opened 2022-09-14 23:02 UTC by atulep

2022-09-28 22:13 UTC, dazuma requested changes

2022-09-28 22:13 UTC, dazuma commented on gapic-generator/templates/default/service/rest/client/method/def/_response_server_streaming.erb
> +Gapic::Rest::ServerStream.new(
Please prefix all fully-qualified types with `::`. i.e. `::Gapic::Rest::ServerStream`. This is to guard against the corner case of some other generated class using the name `Gapic` and messing with constant lookup. Same with all other template code below.

2022-12-12 18:31 UTC, dazuma commented
@atulep Can this be closed now?

2022-12-15 22:30 UTC, atulep commented
Correct. This can be closed after the main PR was submitted.

2022-12-15 22:30 UTC, closed without merging