feat: implements template changes for REST server-streaming.
googleapis/gapic-generator-ruby pull request #844
Opened 2022-11-03 22:54 UTC by atulep

2022-11-04 21:08 UTC, atulep commented on gapic-generator/lib/gapic/presenters/method_rest_presenter.rb
> +      #
Remove

2022-11-11 23:51 UTC, atulep commented on gapic-generator/lib/gapic/presenters/method_rest_presenter.rb
> +      #
Actually, we need it. In `gapic-generator/templates/default/service/rest/client/method/def/_response.erb`, it checks `<%- elsif method.rest.server_streaming? -%>`. I could remove `.rest`, but all other `if` conditions use it, so prefer to leave it as is.

2022-11-16 23:28 UTC, dazuma requested changes

2022-11-16 23:28 UTC, dazuma commented on gapic-generator/templates/default/service/rest/service_stub/method/_def.erb
> +# @return [Faraday::Response]
Please use `::Faraday::Response` (including leading colons)

2022-11-16 23:28 UTC, dazuma commented on gapic-generator/templates/default/service/rest/service_stub/method/_def.erb
> +# @yieldparam chunk [String] The chunk of data received during server streaming.
Please use `::String` (including leading colons)

2022-11-16 23:28 UTC, dazuma commented on gapic-generator/templates/default/service/rest/client/method/docs/_result.erb
> +# @return [Enumerable<<%= method.rest.doc_response_type %>>]
Please use `::Enumerable` (including leading colons)

2022-11-16 23:28 UTC, dazuma commented on shared/test/showcase/echo/expand_test.rb
> +                                 error: {code: 404, message: "my-error-message" }})
Please fix indentation

2022-11-17 22:09 UTC, atulep commented on shared/test/showcase/echo/expand_test.rb
> +                                 error: {code: 404, message: "my-error-message" }})
Done

2022-11-17 22:09 UTC, atulep commented on gapic-generator/templates/default/service/rest/client/method/docs/_result.erb
> +# @return [Enumerable<<%= method.rest.doc_response_type %>>]
Done

2022-11-17 22:09 UTC, atulep commented on gapic-generator/templates/default/service/rest/service_stub/method/_def.erb
> +# @yieldparam chunk [String] The chunk of data received during server streaming.
Done

2022-11-17 22:09 UTC, atulep commented on gapic-generator/templates/default/service/rest/service_stub/method/_def.erb
> +# @return [Faraday::Response]
Done

2022-11-17 22:09 UTC, atulep commented on gapic-generator/lib/gapic/presenters/method_rest_presenter.rb
> +        (@main_method.kind == :normal || @main_method.kind == :server) &&
Done

2022-11-17 22:15 UTC, dazuma approved these changes
I think you need to regenerate the goldens, but otherwise lgtm.

2022-11-30 00:40 UTC, merged